### PR TITLE
Update hiop umpire deps

### PR DESCRIPTION
**Pull request by ashermancinelli**
@cameronrutherford Could you look this over before I open a pr upstream?

### CODE REVIEW

**Comment by cameronrutherford** [comment]
Could you add a variant for `HIOP_BUILD_DOCUMENTATION` in CMake as well with this MR?

**Comment by ashermancinelli** [comment]
> HIOP_BUILD_DOCUMENTATION

happy to, but do we need a dependency on doxygen? I haven't built with that option through spack yet.

**Comment by cameronrutherford** [comment]
I haven't either, but perhaps wanted to add it to the todo list.

**Comment by ashermancinelli** [comment]
[Opened upstream.](https://github.com/spack/spack/pull/26905)

**Pull request closed without merging**
